baseURL = "https://sailingwithdamian.eu/"
languageCode = "en-gb"
title = "Sailing with Damian"
disableKinds = ["RSS"]

[params]
  description = "RYA Yachtmaster Instructor and professional skipper based in the Netherlands"
  author = "Damian Zaremba"
  email = "damian@sailingwithdamian.eu"
  turnstile_site_key = "0x4AAAAAACzlrWRlqvVtAQk9"

[security.http]
mediaTypes = ['^application/octet-stream$']

[menu]
  [[menu.main]]
    name = "About Me"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Resources"
    url = "/resources/"
    weight = 2
